### ISSUE TITLE
Do not replace characters in paths

### ISSUE THREAD

**Issue by autrimpo** [emacs-citar/citar#668]
**Describe the bug**
`file` fields are transformed using `parsebib-TeX-markup-replace-alist`, which results in mangled paths.

**To Reproduce**
1. Add a `file` field to an entry containing `--`.
2. Call `citar-open-files`.
3. Get an error about missing files, as `--` has been replaced with `–` (en dash).

**Expected behavior**
The file is opened correctly.

**Screenshots**
Unnecessary?

**Emacs version:**
`GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)`

**Additional context**
`--` is included in the default alist. It is also used in the Denote naming scheme, creating conflicts.

**Comment by bdarcus** [comment]
Do you have a sense of whether this might be better fixed in parsebib, or if there's an obvious oversight in this codebase?

**Comment by autrimpo** [comment]
Unfortunately, I don't know. I was just trying to figure out why citar couldn't find my files :)

**Comment by joostkremers** [comment]
It's a parsebib issue, because parsebib doesn't allow one to specify which fields to untexify. That needs to be fixed.

It is possible to untexify a single string (see `parsebib-clean-tex-markup`), but that's cumbersome to do from within citar. Better to make parsebib mor flexible.

**Comment by bdarcus** [comment]
Right; so you'd make that change, and we'd want to pass a list of fields to `parsebib-parse`, which would exclude `file` and such (the actual field for this we define in a defcustom)?

**Comment by roshanshariff** [comment]
Depending on how @joostkremers implements this in`parsebib`, do we need any change to `citar--fields-to-parse`? Presumably, `parsebib` would have a list of fields not to untexify, which would include `file`. We would continue to include `file` as one of the fields to parse. Removing `file` from that list would just mean that it's not included in the entry alist, which isn't what we want.

**Comment by bdarcus** [comment]
That's true; it does depend on whether this list of fields here is an exclusion list (more convenient in this case), or an inclusion list. I was assuming the latter.

For sure; let's wait. I was just curious also if we had suggestions for @joostkremers.

**Comment by joostkremers** [comment]
> For sure; let's wait. I was just curious also if we had suggestions for @joostkremers.

Since it's obvious that the `file` field should not be untexified, parsebib should take care of this automatically, without the caller having to worry about it. So yes, I agree an exclusion list built into parsebib makes the most sense. I would do this as a `defvar`, so that it can be `let`-bound around a call to `parsebib-parse-bib-buffer` if the user wants to customise the exclusion list. (`let`-binding is already the way to customise the conversion of CLS-JSON to displayable strings, so this method would be consistent with that.)

Passing an inclusion list to `parsebib-parse-bib-buffer` would also be an option, but it would basically mean that it's up to the caller to ensure that fields such as the `file` field are not untexified, which I think is the wrong approach.

**Comment by joostkremers** [comment]
See if this update to parsebib fixes the issue:

https://github.com/joostkremers/parsebib/commit/994b658b56113914f9ebfbd1e1084c47c353bc76

**Comment by autrimpo** [comment]
I am happy to report that the change from @joostkremers solved the issue for me.

Thank you all for the quick fix!

**Comment by bdarcus** [comment]
I also took this opportunity to remove our function in #669.

Thanks @joostkremers!
