### ISSUE TITLE
Review `citar--make-indicator-symbols`

### ISSUE THREAD

**Issue by bdarcus** [emacs-citar/citar#764]
@aikrahguzar - you originally wrote `citar--symbol-strings`, which I adapted to this new function.

When you get a chance, can you please review to ensure I have the details right?

It works, but I don't quite understand the alignment stuff.

You can see what it's doing in terms of output like:

```elisp
ELISP> (citar--make-indicator-symbols "abc has:notes")
```

Perhaps we can add some more code comments to clarify for the next time?

---------------------------

https://github.com/emacs-citar/citar/blob/0c6a8038e9b7f72c2e6837bd3342eab942c08d0d/citar.el#L868-L888

**Comment by aikrahguzar** [comment]
The problem is that icons are not fixed width and generally that makes alignment very hard. The way around that is to use specified space in the display text property. The details are in the info node  [(elisp) Specified Space](https://www.gnu.org/software/emacs/manual/html_node/elisp/Specified-Space.html).

But basically we say that the last character of the padding should be replaced by a space which stretches to the position we want to. So for example if the icon has string width 1 but occupies 0.9 the space will stretch to occupy 1.1 and if the icon occupies 1.5 it will shrink to occupy 0.5.

The caveats are:
1) One will get a surprise if the last character of padding is not a space.
2) There will again be a surprise if the padding is an empty string.
3) If the icon has string width `n` but occupies more than `n+1` cells the alignment will persist but I have only seen `n` to be 1 or 2 so I think being off by more than one cell is unlikely. 

Emacs 29 has `vtable` which should allow us to do alignment properly but before that this seems like an acceptable hack.

**Comment by bdarcus** [comment]
So is my adaptation correct?

No rush if you haven't had time to determine.

You might also look at the `citar-indicator` defstruct. I made some assumptions that are probably wrong, and so may need to tweak that a little.

**Comment by bdarcus** [comment]
Oh, I also submitted a doom PR based on this :-)

**Comment by aikrahguzar** [comment]
> So is my adaptation correct?

It looks as correct to me as the last version I wrote which is only correct up to the caveats I mentioned.

**Comment by bdarcus** [comment]
Thank you!

**Comment by bdarcus** [comment]
I added an extensive code comment, just an edited version of your first message, in this commit.

https://github.com/emacs-citar/citar/pull/763/commits/3bb0c403eade0aa04b95f453474a05166bd797fe

**Comment by bdarcus** [comment]
On vtable, here's a really cool post!

https://lars.ingebrigtsen.no/2022/04/13/more-vtable-fun/
