### ISSUE TITLE
Request for Nerd Icons Integration in Citar

### ISSUE THREAD

**Issue by LuciusChen** [emacs-citar/citar#797]
**Is your feature request related to a problem? Please describe.**

I'm currently using citar for managing and interacting with my bibliographic references in Emacs. However, I would like to use the nerd-icons package (https://github.com/rainstormstudio/nerd-icons.el) to display appropriate icons for different types of references in citar. Currently, citar does not seem to have support for nerd-icons.

**Describe the solution you'd like**

I would like to see built-in support for nerd-icons in citar. Specifically, this would mean that citar could display different icons based on the type of each reference when displaying reference lists. The mapping of reference types to icons would ideally be customizable.

**Describe alternatives you've considered**

I've considered using all-the-icons, which is a similar package to nerd-icons. However, I prefer the look and feel of nerd-icons, and it would be great if I could use it directly with citar.

**Additional context**

I believe that adding support for nerd-icons would make citar more flexible and visually appealing for users who prefer this icon set. I appreciate your consideration of this feature request.

**Comment by bdarcus** [comment]
Hi!

As a general rule, I don't want to add any icon dependency. I considered, for example, `all-the-icons` at the very beginning, but decided against it, in part because different people have different preferences.

In fact, reducing dependencies is a general priority here; hence why we split off `citar-embark`, and citar-org-roam` is in a separate repository.

What may be reasonable is somehow adding support for users to configure this themselves, as they can now for the "indicators".

I'll need to think about what that would entail. Perhaps a way to convert the plain text reference type strings into symbols; as you say, configurable (an alist defcustom, for example)?

But it's not a high-priority for me personally, and I don't have much time to work on it. But happy to consider a PR.

Or if you want to look into what would be required to add that and report your findings here, that could also be helpful.

**Comment by bdarcus** [comment]
One wrinkle on this:

> Perhaps a way to convert the plain text reference type strings into symbols; as you say, configurable (an alist defcustom, for example)?

Citar supports three different input formats (bibtex, biblatex, and CSL JSON), and hence lists of types. Also, they can be mixed within the same list of files.

**Comment by bdarcus** [comment]
@LuciusChen here's a config for nerd-icons indicators.

https://github.com/emacs-citar/citar/wiki/Indicators#nerd-icons
